-- Wulin Tournament Control Cloud schema
-- Run this entire file once in Supabase Dashboard > SQL Editor.

begin;

create extension if not exists pgcrypto;

create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{2,62}$'),
  name text not null,
  state jsonb not null,
  version bigint not null default 1 check (version >= 1),
  is_public boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by text
);

create index if not exists tournaments_public_slug_idx
  on public.tournaments (slug)
  where is_public = true;

create table if not exists public.tournament_state_history (
  id bigint generated by default as identity primary key,
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  version bigint not null,
  state jsonb not null,
  actor text,
  created_at timestamptz not null default now(),
  unique (tournament_id, version)
);

create index if not exists tournament_state_history_lookup_idx
  on public.tournament_state_history (tournament_id, version desc);

alter table public.tournaments enable row level security;
alter table public.tournament_state_history enable row level security;

-- Public screens can read only events explicitly marked public.
drop policy if exists "Public tournaments are readable" on public.tournaments;
create policy "Public tournaments are readable"
  on public.tournaments
  for select
  to anon, authenticated
  using (is_public = true);

-- Browser clients receive SELECT only. All writes go through the Vercel Function.
grant usage on schema public to anon, authenticated;
grant select on public.tournaments to anon, authenticated;
revoke insert, update, delete, truncate, references, trigger
  on public.tournaments from anon, authenticated;
revoke all on public.tournament_state_history from anon, authenticated;

-- Atomic optimistic-lock save. The expected version prevents two staff devices
-- from silently overwriting each other.
create or replace function public.save_tournament_state(
  p_slug text,
  p_state jsonb,
  p_expected_version bigint,
  p_actor text default 'staff'
)
returns table (new_version bigint, new_updated_at timestamptz)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_tournament_id uuid;
  v_version bigint;
  v_updated_at timestamptz;
begin
  if jsonb_typeof(p_state) <> 'object' then
    raise exception 'INVALID_STATE' using errcode = '22023';
  end if;

  if jsonb_typeof(p_state -> 'settings') <> 'object'
     or jsonb_typeof(p_state -> 'categories') <> 'array'
     or jsonb_typeof(p_state -> 'matches') <> 'array' then
    raise exception 'INVALID_STATE_SHAPE' using errcode = '22023';
  end if;

  update public.tournaments as t
     set state = p_state,
         version = t.version + 1,
         updated_at = now(),
         updated_by = left(coalesce(p_actor, 'staff'), 120)
   where t.slug = p_slug
     and t.version = p_expected_version
  returning t.id, t.version, t.updated_at
       into v_tournament_id, v_version, v_updated_at;

  if not found then
    raise exception 'VERSION_CONFLICT' using errcode = '40001';
  end if;

  insert into public.tournament_state_history
    (tournament_id, version, state, actor)
  values
    (v_tournament_id, v_version, p_state, left(coalesce(p_actor, 'staff'), 120))
  on conflict (tournament_id, version) do nothing;

  -- Keep the latest 250 snapshots per event. This is enough for accidental-edit
  -- recovery without allowing the history table to grow forever.
  delete from public.tournament_state_history as h
   where h.tournament_id = v_tournament_id
     and h.id not in (
       select h2.id
         from public.tournament_state_history as h2
        where h2.tournament_id = v_tournament_id
        order by h2.version desc
        limit 250
     );

  return query select v_version, v_updated_at;
end;
$$;

revoke all on function public.save_tournament_state(text, jsonb, bigint, text)
  from public, anon, authenticated;
grant execute on function public.save_tournament_state(text, jsonb, bigint, text)
  to service_role;

-- Initial production event. Keep this slug aligned with VITE_EVENT_SLUG and EVENT_SLUG.
insert into public.tournaments (slug, name, state, version, is_public, updated_by)
values (
  'wulin-annual-2026',
  '武林年度赛 Tournament Control',
  $state$
  {
    "version": 4,
    "settings": {
      "eventName": "武林年度赛 Tournament Control",
      "autoNext": true,
      "dashboardCatIds": [],
      "prepareMatchIds": [],
      "courts": [
        {"id":"court1","name":"Court 1"},
        {"id":"court2","name":"Court 2"},
        {"id":"court3","name":"Court 3"},
        {"id":"court4","name":"Court 4"},
        {"id":"court5","name":"Court 5"},
        {"id":"court6","name":"Court 6"}
      ]
    },
    "categories": [],
    "matches": []
  }
  $state$::jsonb,
  1,
  true,
  'schema-seed'
)
on conflict (slug) do nothing;

insert into public.tournament_state_history (tournament_id, version, state, actor)
select id, version, state, 'schema-seed'
  from public.tournaments
 where slug = 'wulin-annual-2026'
on conflict (tournament_id, version) do nothing;

-- Enable Postgres Changes for the one-row tournament state table.
do $$
begin
  if not exists (
    select 1
      from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'tournaments'
  ) then
    execute 'alter publication supabase_realtime add table public.tournaments';
  end if;
end;
$$;

commit;
